### ISSUE TITLE
Nicer name for sharing drives via RDP

### ISSUE THREAD

**Issue by scooley** [jterry75/xrdp-init#2]
Right now it's thinclinet or something.  Let's make it something like shared-folders

**Comment by jterry75** [comment]
Ok good idea.

**Comment by theterminator3000** [comment]
I'm not keen on this. Within Windows RDP the drives are seen under a network device tsclient. Shouldn't we have uniformity across platforms?

**Comment by jterry75** [comment]
I agree with the statement about uniformity across platforms. When we do this via windows it will show up via cmd as something like:
```cmd
> \\tsclient\{Drive}
```
And in explorer it will show up under:
```
Redirected drives and folders
```
as an entry called:
```
{Drive} on {Hostname}
```
--
On Ubuntu, XRDP allows us to customize the fuse entry name but not the location. It is hard coded to the env `$HOME\<name>\<drive>`. To match the best we could do is call it:
```bash
> $HOME\tsclient\{drive}
```
and in nautilus it will show up as:
```
tsclient
```
With sub folders
```
{Drive}
```
--

Do you agree with that for a solution?

**Comment by jterry75** [comment]
@cwilhit

**Comment by cwilhit** [comment]
I'm inclined to think UX and intent is more important than uniformity for the sake of uniformity. 

On Windows, the fact that you have a folder called "tsclient" is hidden from the user (unless you're using a shell). All I see when I share the drive is "C on cwilhit-desktop".

In order to get the same experience in Linux, I think calling the folder "shared drives" communicates this idea. Calling the folder "tsclient" gives no immediate insight to the user about what it contains--some users might even be oblivious to the fact that we use a TS client to enable the enhanced session.

**Comment by jterry75** [comment]
This has now been fixed.
